type: custom:vertical-stack-in-card # type: vertical-stack 
style: |
  ha-card {
      border: 1px solid {% if is_state('binary_sensor.global', 'on') %} {{state_attr('binary_sensor.global','level')}} {% else %} Green {% endif %};
  }
cards:
  # - !include natural_events/banner_header.yaml
  - !include natural_events/picture_elements.yaml

  - type: conditional # NSCONDE/VISUALIZZA tutte le cards
    conditions:
      - entity: input_boolean.natural_events
        state: 'on'
    card:
      type: vertical-stack # CARDS VISUALIZZATE SOLO SE INPUT BOOLEAN NATURAL EVENTS ON!!
      cards:

      - type: entities # CONTENITORE MENU Impostazioni fold, SENSORI on
        style: |
          div#states.card-content {padding-block-end: 0;padding-block-start: 0;}
          ha-card {background:none; border-radius: 0px; box-shadow: none;}
        entities:
          - !include natural_events/fold_settings.yaml
          - !include natural_events/fold_meteoalert.yaml
          - !include natural_events/fold_geoalert.yaml

      - !include natural_events/markdown_gdacs.yaml
      - !include natural_events/markdown_quake.yaml
      - !include natural_events/markdown_dpc.yaml
      - !include natural_events/markdown_burze.yaml
      - !include natural_events/markdown_meteoalarm.yaml
      - !include natural_events/markdown_meteoalarm_custom.yaml
