type: vertical-stack
cards:
  - type: markdown
    style: |
      @keyframes blink {
        30% {
          background: {% if is_state('group.natural_events', 'on') %} gray {% endif %};
        }
      }
      ha-card {
        animation: {% if is_state('group.natural_events', 'on') %} blink 2s linear 3 {% endif %};
        border-style: solid;
        box-shadow: none;
        {% if is_state('group.natural_events', 'on') %}
        background: {{states('sensor.natural_events_level')}};
        border-color: {{states('sensor.natural_events_level')}};
        color: {% if states('sensor.natural_events_level') in ['White','Yellow'] %} red; {% else %} yellow; {% endif %}
        {% else %}
        background: Green;
        border-color: Green;
        {% endif %}
        }
      }
    content: >-

      {% if is_state('group.natural_events', 'on') %} <font
      size="4"><center><ha-icon icon="mdi:alert" style="width: 48px; height:
      48px;"></ha-icon>&nbsp; ALLERTA EVENTI CRITICI</center></font> {% else %}
      <font size="4"><center><ha-icon icon="mdi:shield-check-outline"
      style="width;48px; height: 48px;"></ha-icon>&nbsp; NESSUN EVENTO SEGNALATO
      {% set summary = states('sensor.dark_sky_daily_summary') %}

      <center></font> <font size="3">{{'' if summary  == 'unknown' else summary }}</font> {% endif %}
  - type: entities
    title: ''
    style: |
      ha-card { border-radius: 0px; box-shadow: none;}
    show_header_toggle: false
    entities:
      - type: 'custom:fold-entity-row'
        head: group.meteoalert
        entities:
          - entity: binary_sensor.meteoalarm
            secondary_info: last-changed
            icon: 'mdi:weather-pouring'
          - entity: binary_sensor.burze_storms_nearby
            secondary_info: last-changed
          - binary_sensor.dpc_temporali_oggi
          - binary_sensor.dpc_temporali_domani
          - automation.natural_events_meteoalarm_notifications
          - automation.natural_events_burze_notifications
          - input_select.meteo_map
          - input_select.meteo_iframe
          - input_boolean.natural_events_send_image
      - type: 'custom:fold-entity-row'
        head: group.geoalert
        entities:
          - entity: binary_sensor.lastquake
            secondary_info: last-changed
            icon: 'mdi:earth'
          - binary_sensor.dpc_idraulico_oggi
          - binary_sensor.dpc_idraulico_domani
          - binary_sensor.dpc_idrogeologico_oggi
          - binary_sensor.dpc_idrogeologico_domani
          - automation.natural_events_quake_notifications
          - automation.natural_events_protezione_civile_notifications
  - type: 'custom:auto-entities'
    show_empty: false
    filter:
      include:
        - entity_id: binary_sensor.dpc_*
          state: 'on'
          attributes:
            level: '> 0'
    card:
      type: markdown
      style: |
        ha-card { border-radius: 0px; box-shadow: none;}
        .card-content {padding: 0}
      content: >-
        ___

        ## PROTEZIONE CIVILE

        {% set color = {0:'White', 1:'Green', 2:'Yellow', 3:'Orange', 4:'Red'}
        %} {% for e in config.entities %}
          <font color= {{color[state_attr(e.entity, 'level')|int]}}><ha-icon icon="{{ 'mdi:numeric-' ~ state_attr(e.entity, 'level')|int ~ '-box'}}" style="width: 36px; height: 36px;"></ha-icon> {{state_attr(e.entity, 'friendly_name')}}.</font><font> Zona {{ state_attr(e.entity,'zona_info')}}.</font><br>
        {%- endfor %}

        [Protezione Civile](http://www.protezionecivile.it/home) ~ [Vigilanza
        Meteo](http://www.protezionecivile.gov.it/dettaglio/-/journal_content/56/20182/1131180?refererPlid=42041&controlPanelCategory=current_site.content)
        ~ [Criticità
        Idro](http://www.protezionecivile.gov.it/attivita-rischi/meteo-idro/attivita/previsione-prevenzione/centro-funzionale-centrale-rischio-meteo-idrogeologico/previsionale/bollettini-criticita/bollettino-odierno)
        ~ [Radar](http://www.protezionecivile.gov.it/radar-dpc)
  - type: conditional
    conditions:
      - entity: binary_sensor.lastquake
        state: 'on'
    card:
      type: markdown
      style: |
        ha-card {border-radius: 0px; box-shadow: none;}
      content: |
        ___
        ### TERREMOTI - ULTIME 24h


          {% set data_utc = state_attr('binary_sensor.lastquake', 'publication_date') %}
          {% set magnitudo = (state_attr('binary_sensor.lastquake', 'magnitude')|float) if not none else '0' %}
          {% set code = {0:'White', 1:'Green', 2:'Yellow', 3:'Orange', 4:'Red'} %}
          {% set color = code[state_attr('binary_sensor.lastquake', 'level')|int] %}
          <font color={{color}}>{{as_timestamp(data_utc)|timestamp_custom ('%H:%M:%S del %d-%m-%Y')}}</font> 

          Un terremoto di magnitudo <font color={{color}}> {{magnitudo}} </font> 
          è avvenuto nella zona: [{{state_attr('binary_sensor.lastquake', 'region')}}](https://www.google.com/maps/search/?api=1&query={{state_attr('binary_sensor.lastquake', 'latitude')}},{{state_attr('binary_sensor.lastquake', 'longitude')}})
          a <font color={{color}}> {{state_attr('binary_sensor.lastquake', 'distance')}} </font> km da casa,
          con coordinate geografiche (lat, lon) {{state_attr('binary_sensor.lastquake', 'latitude')}}, {{state_attr('binary_sensor.lastquake', 'longitude')}}

          {% if magnitudo >= 3|int %}
          [Shakemap]({{state_attr('binary_sensor.lastquake', 'image_url')}}) ~ 
          [PGA](http://shakemap.rm.ingv.it/shake/{{state_attr('binary_sensor.lastquake', 'short_id')}}/download/pga.jpg) ~ 
          [PGV](http://shakemap.rm.ingv.it/shake/{{state_attr('binary_sensor.lastquake', 'short_id')}}/download/pgv.jpg) ~ 
          [TvMap](http://shakemap.rm.ingv.it/shake/{{state_attr('binary_sensor.lastquake', 'short_id')}}/download/tvmap.jpg) ~ 
          [TvMap2](http://shakemap.rm.ingv.it/shake/{{state_attr('binary_sensor.lastquake', 'short_id')}}/download/tvmap.jpg) ~ 
          [HaiSentitoIlTerremoto](http://eventi.haisentitoilterremoto.it/{{state_attr('binary_sensor.lastquake', 'short_id')}}/{{state_attr('binary_sensor.lastquake', 'short_id')}}_mcs.jpg)


          <img style="border: 2px solid {{color}};" src="{{state_attr('binary_sensor.lastquake', 'image_url')}}"/>
          {% endif %}

          [INGV](http://cnt.rm.ingv.it)
  - type: conditional
    conditions:
      - entity: binary_sensor.burze_storms_nearby
        state: 'on'
    card:
      type: markdown
      style: |
        ha-card {border-radius: 0px; box-shadow: none;}
      content: |
        ___
        ### TEMPORALI


          <font color= "#4caf50">{{state_attr('binary_sensor.burze_storms_nearby', 'number')}}</font><font color= "yellow"><ha-icon icon="mdi:flash" style="width: 24px; height: 24px;"></ha-icon></font> in <font color= "#4caf50"> {{state_attr('binary_sensor.burze_storms_nearby', 'period')}}</font> <font>minuti</font>.
          <font>Il più vicino è caduto a </font><font color= "#4caf50"> {{state_attr('binary_sensor.burze_storms_nearby', 'distance')}} Km </font> a <font color= "#4caf50"> {{states('sensor.burze_direction')}} </font> da casa. 

          [Burze](https://burze.dzis.net) ~ [Blitzortung](http://map.blitzortung.org/#5.11/43.00/13.00)
  - type: conditional
    conditions:
      - entity: binary_sensor.meteoalarm
        state: 'on'
    card:
      type: markdown
      style: |
        ha-card {border-radius: 0px; box-shadow: none;}
      content: >-
        ___


        <font size="4" color= {{states('sensor.meteoalarm_level')}}> <ha-icon
        icon="{{state_attr('sensor.meteoalarm_level', 'icon')}}" style="width:
        36px; height: 36px;"></ha-icon> </font> <font size="4" color=
        {{states('sensor.meteoalarm_level')}}> <ha-icon
        icon="{{state_attr('sensor.meteoalarm_type', 'icon')}}" style="width:
        36px; height: 36px;"></ha-icon></font> <font size="4" color=
        {{states('sensor.meteoalarm_level')}}>
        {{state_attr('binary_sensor.meteoalarm', 'event')}} </font><font
        size="4" color= grey> {{state_attr('binary_sensor.meteoalarm',
        'urgency')}} </font>
          {% set start = state_attr('binary_sensor.meteoalarm', 'effective') %}
          {% set end = state_attr('binary_sensor.meteoalarm', 'expires') %}
        <font><center>{{as_timestamp(start)|timestamp_custom ('Valido dalle ore
        **%H:%M** del **%d/%m**')}} {{as_timestamp(end)|timestamp_custom (' alle
        ore **%H:%M** del **%d/%m**')}}</center></font>

        **Titolo**

        <font color= "#4caf50"> {{state_attr('binary_sensor.meteoalarm',
        'headline')}} </font>


        **Descrizione**

        <font color= "#4caf50"> {{state_attr('binary_sensor.meteoalarm',
        'description')}} </font>


        **Istruzioni**

        <font color= "#4caf50"> {{state_attr('binary_sensor.meteoalarm',
        'instruction')}} </font>

        [MeteoAlarm]({{state_attr('binary_sensor.meteoalarm', 'web')}}) 
  - type: conditional
    conditions:
      - entity: group.natural_events
        state: 'off'
    card:
      type: picture-entity
      style: |
        ha-card { border-radius: 0px; box-shadow: none;}
      entity: sun.sun
      state_image:
        above_horizon: >-
          https://api.sat24.com/animated/IT/visual/3/Central%20European%20Standard%20Time/3065655'
          width=845 height=615
        below_horizon: >-
          https://api.sat24.com/animated/IT/infraPolair/3/Central%20European%20Standard%20Time/2523464'
          width=845 height=615
  - type: conditional
    conditions:
      - entity: group.meteoalert
        state: 'on'
      - entity: input_select.meteo_map
        state_not: Nessuna
    card:
      type: picture-entity
      style: |
        ha-card {
          border-style: solid; 
          border-color: {% if is_state('group.meteoalert', 'on') %} {{ states('sensor.meteoalarm_level') }} {% else %} Green {% endif %}; 
          border-radius: 1px; 
          box-shadow: none;
        }
      title: Nuvole
      entity: input_select.meteo_map
      tap_action:
        action: call-service
        service: input_select.select_next
        service_data:
          entity_id: input_select.meteo_map
        hold_action:
          action: call-service
          service: input_select.select_previous
          service_data:
            entity_id: input_select.meteo_map
      state_image:
        Nuvole e Sole: >-
          https://api.sat24.com/animated/IT/visual/3/Central%20European%20Standard%20Time/3065655'
          width=845 height=615
        Nuvole Infrared: >-
          https://api.sat24.com/animated/IT/infraPolair/3/Central%20European%20Standard%20Time/2523464'
          width=845 height=615
        Pioggia: >-
          https://api.sat24.com/animated/IT/rainTMC/3/Central%20European%20Standard%20Time/3872070'
          width=845 height=615
        Neve: >-
          https://api.sat24.com/animated/EU/snow/3/Central%20European%20Standard%20Time/4614822'
          width=845 height=615
        Burze: 'https://burze.dzis.net/italia_fulmine_lebhaft_gruppi.gif'
        WWLLN: 'https://wwlln.net/WWLLN_movies/Movie_of_Lightning_in_EurAfrica_BIG.gif'
      entities:
        - entity: input_select.meteo_map
  - type: conditional
    conditions:
      - entity: group.natural_events
        state: 'on'
    card:
      type: conditional
      conditions:
        - entity: input_select.meteo_iframe
          state: Posizione Geografica
      card:
        type: map
        style: |
          ha-card {
            border-radius: 1px; 
            box-shadow: none;
          }
        geo_location_sources:
          - wwlln
          - ingv_centro_nazionale_terremoti
        entities:
          - zone.home
          - zone.geoalert
          - zone.meteoalert
        dark_mode: false
        default_zoom: 10
        aspect_ratio: 100%
  - type: conditional
    conditions:
      - entity: group.meteoalert
        state: 'on'
    card:
      type: conditional
      conditions:
        - entity: input_select.meteo_iframe
          state: Windy Alert
      card:
        type: iframe
        style: |
          ha-card {
            border-radius: 0px; 
            box-shadow: none;
          }
        aspect_ratio: 100%
        url: >-
          https://embed.windy.com/embed2.html?lat=42.000&lon=12.000&zoom=5&level=surface&overlay=capAlerts&menu=&type=map&location=coordinates&detail=&detailLat=42.000&detailLon=12.000
