type: entities # Card Principale Entità
style: |
  ha-card {
      border-color: {% if is_state('group.natural_events', 'on') %} {{states('sensor.natural_events_level')}} {% else %} Green {% endif %};
      border-style: solid;
      border-width: 0px 1px 1px 1px;
    #background: --ha-card-background;
  }
  .card-content {
    padding: 0;
  }
entities:
  - type: custom:hui-markdown-card # TESTATINA PRINCIPALE
    style: |
      @keyframes blink {
        30% {
          background: {% if is_state('group.natural_events', 'on') %} gray {% endif %};
        }
      }
      ha-card {
        animation: {% if is_state('group.natural_events', 'on') %} blink 2s linear 3 {% endif %};
        #border-radius: 5px 5px 0px 0px;
        border-style: solid;
        box-shadow: none;
        {% if is_state('group.natural_events', 'on') %}
        background: {{states('sensor.natural_events_level')}};
        border-color: {{states('sensor.natural_events_level')}};
        color: {% if states('sensor.natural_events_level') in ['White','Yellow'] %} red; {% else %} yellow; {% endif %}
        {% else %}
        background: Green;
        border-color: Green;
        {% endif %}
        }
      }
    content: >-
      ## <center>
      {% if is_state('group.natural_events', 'on') %} 
      <ha-icon icon="mdi:alert" style="width: 48px; height: 48px;"></ha-icon> &nbsp; ALLERTA EVENTI CRITICI
      {% else %} 
      <ha-icon icon="mdi:shield-check" style="width: 48px; height: 48px;"></ha-icon> &nbsp; NESSUN EVENTO CRITICO

      {{states('sensor.dark_sky_daily_summary')}}
      {% endif %}</center>

  - type: custom:hui-entities-card # MENU Impostazioni fold, SENSORI on
    style: |
      ha-card {
        background:none; border-radius: 0px; box-shadow: none; 
      }
    entities:
      - type: custom:auto-entities # MENU Impostazioni fold
        show_empty: false
        filter:
          include:
            - attributes:
                package: Natural_events
          exclude:
            - domain: binary_sensor
            - domain: group
            - domain: sensor
            - domain: script
            - domain: zone
        card:
          type: custom:fold-entity-row
          style: |
            :host {
              color: {% if is_state(config.entity, 'on') %} yellow {% endif %};
            }
          head: input_boolean.natural_events

      - type: custom:fold-entity-row
        head: group.meteoalert
      - type: custom:fold-entity-row
        head: group.geoalert

      - type: custom:auto-entities # SENSORI on
        filter:
          include:
            - domain: binary_sensor
              state: 'on'
              attributes:
                  package: Natural_events
              options:
                secondary_info: last-changed
                style: |
                  :host {
                    {% set color = {0:'White', 1:'Green', 2:'Yellow', 3:'Orange', 4:'Red'} %}
                    color: {% if 'dpc' in config.entity %} {{color[state_attr(config.entity, 'level')|int]}} 
                            {% elif 'meteoalarm' in config.entity %} {{states('sensor.meteoalarm_level')}}
                             {% elif 'quake' in config.entity %} {{color[state_attr('binary_sensor.lastquake', 'level')|int]}}
                           {% endif %};
                  }
        card:
          type: entities
          show_empty: false
          style: |
            ha-card {background: none; border-radius: 0px; box-shadow: none;}
            .card-content {padding: 0}

  - type: custom:hui-conditional-card # NSCONDE/VISUALIZZA tutte le cards
    conditions:
      - entity: input_boolean.natural_events
        state: 'on'
    card:
      type: entities
      style: |
        ha-card {border-radius: 0px; box-shadow: none; background: none;}
      # CARDS VISUALIZZATE SOLO SE INPUT BOOLEAN NATUAR EVENTS ON!!
      entities:
        - type: custom:auto-entities # TERREMOTO conditional
          show_empty: false
          filter:
            include:
              - entity_id: binary_sensor.lastquake
                state: 'on'
          card:
            type: custom:text-divider-row # TEREMOTO divider
            text:  TERREMOTO

        - type: custom:auto-entities # TERREMOTO markdown
          show_empty: false
          filter:
            include:
              - entity_id: binary_sensor.lastquake
                state: 'on'
          card:
            type: markdown
            style: >
              ha-card {background: none; border-radius: 0px; box-shadow: none; color: gray;}
              .card-content {padding: 0}
            content: >-
              {% set data_utc = state_attr('binary_sensor.lastquake', 'publication_date') %}
              {% set magnitudo = (state_attr('binary_sensor.lastquake', 'magnitude')|float) if not none else '0' %}
              {% set code = {0:'White', 1:'Green', 2:'Yellow', 3:'Orange', 4:'Red'} %}
              {% set color = code[state_attr('binary_sensor.lastquake', 'level')|int] %}
              {% set lat = state_attr('binary_sensor.lastquake', 'latitude') %}
              {% set lon = state_attr('binary_sensor.lastquake', 'longitude') %}
              <font color={{color}}>{{as_timestamp(data_utc)|timestamp_custom ('%H:%M:%S del %d-%m-%Y')}}</font>


              Un terremoto di magnitudo <font color={{color}}> {{magnitudo}} </font> 
              è avvenuto nella zona: [{{state_attr('binary_sensor.lastquake', 'region')}}](https://www.google.com/maps/search/?api=1&query={{state_attr('binary_sensor.lastquake', 'latitude')}},{{state_attr('binary_sensor.lastquake', 'longitude')}})
              a <font color={{color}}> {{state_attr('binary_sensor.lastquake', 'distance')}} </font> km da casa,
              con coordinate geografiche (lat, lon) {{lat}}, {{lon}}. 
              
              Tu ti trovi a {{distance(lat, lon, 'device_tracker.oneplus_5t') | round(1)}} km dall'epicentro.


              {% if magnitudo >= 3|int %}
              [Shakemap]({{state_attr('binary_sensor.lastquake', 'image_url')}}) ~ 
              [PGA](http://shakemap.rm.ingv.it/shake/{{state_attr('binary_sensor.lastquake', 'short_id')}}/download/pga.jpg) ~ 
              [PGV](http://shakemap.rm.ingv.it/shake/{{state_attr('binary_sensor.lastquake', 'short_id')}}/download/pgv.jpg) ~ 
              [TvMap](http://shakemap.rm.ingv.it/shake/{{state_attr('binary_sensor.lastquake', 'short_id')}}/download/tvmap.jpg) ~ 
              [TvMap2](http://shakemap.rm.ingv.it/shake/{{state_attr('binary_sensor.lastquake', 'short_id')}}/download/tvmap.jpg) ~ 
              [HaiSentitoIlTerremoto](http://eventi.haisentitoilterremoto.it/{{state_attr('binary_sensor.lastquake', 'short_id')}}/{{state_attr('binary_sensor.lastquake', 'short_id')}}_mcs.jpg)


              <img style="border: 2px solid {{color}};" src="{{state_attr('binary_sensor.lastquake', 'image_url')}}"/>
              {% endif %}


              [INGV](http://terremoti.ingv.it/) ~ [HaiSentitoIlTerremoto Web](http://www.haisentitoilterremoto.it/)

        - type: custom:hui-conditional-card # TERREMOTO geolocation
          conditions:
            - entity: binary_sensor.lastquake
              state: 'on'
          card:
              type: conditional
              conditions:
                - entity: input_select.meteo_iframe
                  state: 'Posizione Geografica'
              card:
                type: map
                style: |
                  ha-card {
                    border-radius: 0px;
                    border: solid 1px var(--accent-color); 
                    box-shadow: none;
                    margin: 16px;
                  }
                entities:
                  - zone.geoalert
                geo_location_sources:
                  - ingv_centro_nazionale_terremoti
                dark_mode: true
                default_zoom: 10
                aspect_ratio: 100%

        - type: custom:auto-entities # DPC conditional
          show_empty: false
          filter:
            include:
              - entity_id: "*binary_sensor.dpc_*"
                state: 'on'
          card:
            type: custom:text-divider-row # DPC divider
            text: PROTEZIONE CIVILE

        - type: custom:auto-entities # DPC markdown
          show_empty: false
          filter:
            include:
              - entity_id: "*binary_sensor.dpc_*"
                state: 'on'
                attributes:
                    level: "> 0"
          card:
            type: markdown
            style: |
              ha-card {background: none; border-radius: 0px; box-shadow: none;}
              .card-content {padding: 0}
            content: >
              {% set color = {0:'White', 1:'Green', 2:'Yellow', 3:'Orange', 4:'Red'} %}
              {% for e in config.entities %}


              <font color= {{color[state_attr(e.entity, 'level')|int]}}>
              <ha-icon icon="{{ 'mdi:numeric-' ~ state_attr(e.entity, 'level')|int ~ '-box'}}" style="width: 36px; height: 36px;"></ha-icon> 
              {{state_attr(e.entity, 'friendly_name')}} - {{state_attr(e.entity, 'allerta')}} {{state_attr(e.entity, 'info')}}</font>
              {%- endfor %}


              [Protezione Civile](http://www.protezionecivile.it/home) ~ [Vigilanza Meteo](http://www.protezionecivile.gov.it/dettaglio/-/journal_content/56/20182/1131180?refererPlid=42041&controlPanelCategory=current_site.content)
              ~ [Criticità Idro](http://www.protezionecivile.gov.it/attivita-rischi/meteo-idro/attivita/previsione-prevenzione/centro-funzionale-centrale-rischio-meteo-idrogeologico/previsionale/bollettini-criticita/bollettino-odierno) ~ [Radar](http://www.protezionecivile.gov.it/radar-dpc)

        - type: custom:auto-entities # BURZE conditional
          show_empty: false
          filter:
            include:
              - entity_id: binary_sensor.burze_storms_nearby
                state: 'on'
          card:
            type: entities
            style: |
              ha-card {background: none; border-radius: 0px; box-shadow: none;}
              .card-content {padding: 0;}
            show_header_toggle: false
            entities:
              - type: custom:text-divider-row
                text: BURZE

              - type: custom:auto-entities # BURZE markdown
                show_empty: false
                filter:
                  include:
                    - entity_id: binary_sensor.burze_storms_nearby
                      state: 'on'
                card:
                  type: markdown
                  style: |
                    ha-card {background: none; border-radius: 0px; box-shadow: none;}
                  content: >-
                    <font color= #4caf50>{{state_attr('binary_sensor.burze_storms_nearby', 'number')}}</font><font color= yellow><ha-icon icon="mdi:flash" style="width: 24px; height: 24px; transform: rotate(35deg);"></ha-icon></font> in <font color= #4caf50> {{state_attr('binary_sensor.burze_storms_nearby', 'period')}}</font> minuti.
                    Il più vicino è caduto a <font color= #4caf50> {{state_attr('binary_sensor.burze_storms_nearby', 'distance')}} Km </font> a <font color= #4caf50> {{states('sensor.burze_direction')}} </font>
                    </font> da casa.


                    [Burze](https://burze.dzis.net) ~ [Blitzortung](http://map.blitzortung.org/#5.11/43.00/13.00) 

        - type: custom:auto-entities # METEOALARM divider
          show_empty: false
          filter:
            include:
              - entity_id: binary_sensor.meteoalarm
                state: 'on'
          card:
            type: custom:text-divider-row
            text: METEO ALARM

        - type: custom:auto-entities # METEOALARM markdown conditional
          show_empty: false
          filter:
            include:
              - entity_id: binary_sensor.meteoalarm
                state: 'on'
          card:
            type: markdown
            style: |
              ha-card {background: none; border-radius: 0px; box-shadow: none;}
            content: >
              ## <font color= {{states('sensor.meteoalarm_level')}}> <ha-icon icon="{{state_attr('sensor.meteoalarm_level', 'icon')}}" style="width: 36px; height: 36px;"></ha-icon> </font>
              <font color= {{states('sensor.meteoalarm_level')}}> <ha-icon icon="{{state_attr('sensor.meteoalarm_type', 'icon')}}" style="width: 36px; height: 36px;"></ha-icon></font>
              <font color= {{states('sensor.meteoalarm_level')}}> {{state_attr('binary_sensor.meteoalarm', 'event')}}
              </font><font color= grey> {{state_attr('binary_sensor.meteoalarm', 'urgency')}} </font>
              
              {% set start = state_attr('binary_sensor.meteoalarm', 'effective') %}
              {% set end = state_attr('binary_sensor.meteoalarm', 'expires') %}
              <font><center> {{as_timestamp(start)|timestamp_custom ('Valido dalle ore **%H:%M** del **%d/%m**')}}
              {{as_timestamp(end)|timestamp_custom (' alle ore **%H:%M** del **%d/%m**')}} </center></font>


              **Titolo**

              <font color= grey> {{state_attr('binary_sensor.meteoalarm', 'headline')}} </font>


              **Descrizione**

              <font color= grey> {{state_attr('binary_sensor.meteoalarm', 'description')}} </font>


              **Istruzioni**

              <font color= grey> {{state_attr('binary_sensor.meteoalarm', 'instruction')}} </font>


              [MeteoAlarm]({{state_attr('binary_sensor.meteoalarm', 'web')}}) 

        - type: custom:hui-conditional-card # MAPPA Giorno/Notte
          conditions:
            - entity: group.natural_events
              state: 'off'
          card:
              type: picture-entity
              style: |
                ha-card {
                  border-radius: 0px; 
                  border: solid 1px var(--accent-color);
                  box-shadow: none;
                  margin: 16px;
                }
              entity: sun.sun
              state_image:
                "above_horizon": https://api.sat24.com/animated/IT/visual/3/Central%20European%20Standard%20Time/3065655' width=845 height=615
                "below_horizon": https://api.sat24.com/animated/IT/infraPolair/3/Central%20European%20Standard%20Time/2523464' width=845 height=615

        - type: custom:hui-conditional-card # MAPPE meteo
          conditions:
            - entity: group.meteoalert
              state: 'on'
            - entity: input_select.meteo_map
              state_not: 'Nessuna'
          card:
            type: picture-entity
            style: |
              ha-card {
                border-radius: 0px; 
                border: solid 1px var(--accent-color);
                box-shadow: none;
                margin: 16px;
              }
            title: Nuvole
            entity: input_select.meteo_map
            tap_action:
              action: call-service
              service: input_select.select_next
              service_data:
                entity_id: input_select.meteo_map
            hold_action:
              action: call-service
              service: input_select.select_previous
              service_data:
                entity_id: input_select.meteo_map
            state_image:
              "Nuvole e Sole": https://api.sat24.com/animated/IT/visual/3/Central%20European%20Standard%20Time/3065655' width=845 height=615
              "Nuvole Infrared": https://api.sat24.com/animated/IT/infraPolair/3/Central%20European%20Standard%20Time/2523464' width=845 height=615
              "Pioggia": https://api.sat24.com/animated/IT/rainTMC/3/Central%20European%20Standard%20Time/3872070' width=845 height=615
              "Neve": https://api.sat24.com/animated/EU/snow/3/Central%20European%20Standard%20Time/4614822' width=845 height=615 
              "Burze": https://burze.dzis.net/italia_fulmine_lebhaft_gruppi_ne.gif
              "WWLLN": https://wwlln.net/WWLLN_movies/Movie_of_Lightning_in_EurAfrica_BIG.gif
              "Nessuna" : none
            entities: 
              - entity: input_select.meteo_map

        - type: custom:hui-conditional-card # IFRAME wwlln
          conditions:
            - entity: binary_sensor.burze_storms_nearby
              state: 'on'
          card:
              type: conditional
              conditions:
                - entity: input_select.meteo_iframe
                  state: 'Posizione Geografica'
              card:
                type: map
                style: |
                  ha-card {
                    border-radius: 0px;
                    border: solid 1px var(--accent-color); 
                    box-shadow: none;
                    margin: 16px;
                  }
                entities:
                  - zone.meteoalert
                geo_location_sources:
                  - wwlln
                dark_mode: true
                default_zoom: 8
                aspect_ratio: 100%

        - type: custom:hui-conditional-card # IFRAME windy
          conditions:
            - entity: group.geometeoalert
              state: 'on'
          card:
              type: conditional
              conditions:
                - entity: input_select.meteo_iframe
                  state: 'Windy Alert'
              card:
                type: iframe
                style: |
                  ha-card {
                    border-radius: 0px;
                    border: solid 1px var(--accent-color); 
                    box-shadow: none;
                    margin: 16px;
                  }
                aspect_ratio: 100%
                url: https://embed.windy.com/embed2.html?lat=42.000&lon=12.000&zoom=5&level=surface&overlay=capAlerts&menu=&type=map&location=coordinates&detail=&detailLat=42.000&detailLon=12.000
