## Card CONTENITORE Principale
# type: custom:stack-in-card 
# mode: vertical
# type: vertical-stack 
type: custom:vertical-stack-in-card 
style: |
  ha-card {
      {# background: rgb(63,94,251); #}
      {# background: radial-gradient(circle, rgba(63,94,251,1) 0%, rgba(210,210,210,1) 100%); #}
      {# background-color: trasparent; #}
      border: 1px solid {% if is_state('binary_sensor.global', 'on') %} {{state_attr('binary_sensor.global','level')}} {% else %} Green {% endif %};
  }
# style:
#   .: |
#     ha-card {
#       --ha-card-box-shadow: none;
#       background-color: transparent;
#       border-radius: none;
#       border: 1px solid {% if is_state('binary_sensor.global', 'on') %} {{state_attr('binary_sensor.global','level')}} {% else %} Green {% endif %};
#     }
cards:
  - !include natural_events/markdown_header.yaml
  # - !include natural_events/banner_header.yaml
  # - !include natural_events/custom_button_header.yaml
  # - !include natural_events/custom_button_header2.yaml
  # - !include natural_events/picture_elements.yaml
  - type: conditional # CARDS VISUALIZZATE SOLO SE INPUT BOOLEAN NATURAL EVENTS ON!!
    conditions:
      - entity: input_boolean.natural_events
        state: 'on'
    card:
      type: vertical-stack
      cards:
        - type: entities # CONTENITORE MENU Impostazioni fold
          style: |
            div#states.card-content {padding-block-end: 0;padding-block-start: 0;}
            ha-card {background:none; border-radius: 0px; box-shadow: none;}
          entities:
            - !include natural_events/fold_settings.yaml
            - !include natural_events/fold_meteoalert.yaml
            - !include natural_events/fold_geoalert.yaml

  - type: conditional # CARDS VISUALIZZATE SOLO SE INPUT BOOLEAN NATURAL EVENTS OFF!!
    conditions:
      - entity: input_boolean.natural_events
        state: 'off'
    card:
      !include natural_events/auto_sensors.yaml

  - type: conditional # CARDS VISUALIZZATE SOLO SE INPUT BOOLEAN NATURAL EVENTS ON!!
    conditions:
      - entity: input_boolean.natural_events
        state: 'on'
    card:
      type: vertical-stack 
      cards:
        - !include natural_events/markdown_gdacs.yaml
        - !include natural_events/markdown_quake.yaml
        - !include natural_events/markdown_dpc.yaml
        - !include natural_events/markdown_burze.yaml
        - !include natural_events/markdown_meteoalarm.yaml
        - !include natural_events/markdown_meteoalarm_custom.yaml

  - !include natural_events/picture_map_meteo.yaml
  - !include natural_events/map_geo_location.yaml
  - !include natural_events/iframe_map_windy.yaml

