type: 'custom:banner-card'
heading: [mdi:alarm-light,Eventi Naturali, mdi:alarm-light]
style: |
  {% set global = 'binary_sensor.global' %}
  @keyframes blink {
    30% {
      background: {% if is_state(global, 'on') %} gray {% endif %};
    }
  }
  ha-card {
    {% if is_state(global, 'on') %}
    animation:  blink 2s linear 3;
    border: 1px solid {{state_attr(global,'level')}};
    border-radius: var(--ha-card-border-radius) var(--ha-card-border-radius) 0px 0px;
    box-shadow: none;
    background: {{state_attr(global,'level')}};
    --bc-heading-color-dark: {% if state_attr(global,'level') in ['White','Yellow'] %} red; {% else %} yellow; {% endif %}
    {% else %}
    background: Green;
    {% endif %}
    --keep-background: true;
    --bc-font-size-heading: 1.5em;
    --bc-font-size-entity-value: 1em;
    }
  }