type: custom:fold-entity-row # 2 group.geoalert
head: 
  entity: group.geoalert
  state_color: true
  style: |
    :host {
      {% if is_state('group.geoalert', 'on') %} 
      --paper-item-icon-color: var(--paper-item-icon-active-color);
      {% endif %}
    }
group_config:
  state_color: true
  secondary_info: last-changed
  style: |
    :host {
      {% set color = {0:'var(--primary-text-color)', 1:'Green', 2:'Yellow', 3:'Orange', 4:'Red'} %}
      color: {% if 'dpc' in config.entity %} {{color[state_attr(config.entity, 'level')|int]}} 
              {% elif 'meteoalarm' in config.entity %} {{state_attr('binary_sensor.global','meteoalarm_level')}}
              {% elif 'quake' in config.entity and states('binary_sensor.lastquake') == 'on' %} {{color[state_attr('binary_sensor.lastquake', 'level')|int]}}
            {% endif %};
      {% if 'meteoalarm_custom' in config.entity %} --paper-item-icon-color: var(--paper-item-icon-active-color);{% endif %}
    }