type: conditional
conditions:
  - entity: input_select.geo_map
    state: 'Posizione Geografica'
card:
  type: map
  style: |
    ha-card {
      border-radius: var(--ha-card-border-radius);
      border: solid 1px var(--accent-color); 
      box-shadow: none;
      margin: 16px;
    }
  entities:
    - entity: person.claudio
  geo_location_sources:
    - all
  dark_mode: true
  default_zoom: 8
  aspect_ratio: '16:9' #100%
  hours_to_show: 72