type: markdown #custom:hui-element #custom:hui-markdown-card # TESTATINA PRINCIPALE
# card_type: markdown
style: |
  {% set global = 'binary_sensor.global' %}
  @keyframes blink {
    30% {
      background: {% if is_state(global, 'on') %} gray {% endif %};
    }
  }
  ha-card {
    border-radius: var(--ha-card-border-radius) var(--ha-card-border-radius) 0px 0px;
    border-style: solid; box-shadow: none;
    {% if is_state(global, 'on') %}
    animation: blink 2s linear 3;
    background: {{state_attr(global,'level')}};
    border-color: {{state_attr(global,'level')}};
    color: {% if state_attr(global,'level') in ['White','Yellow','Orange'] %} var(--disabled-text-color) {% endif %};
    {% else %}
    background: Green; border-color: Green;
    {% endif %}
    }
  }
content: |
  {% set global = 'binary_sensor.global' %}
  {% set summary = states('sensor.dark_sky_daily_summary') %}
  {% set risk = {'Green':'Verde', 'Yellow':'Gialla', 'Orange':'Arancione', 'Red':'Rossa'} %}
  {% if is_state(global, 'on') %}
  <center><b><ha-icon icon="mdi:alarm-light"></ha-icon>&nbsp;EVENTI NATURALI - ALLERTA <ha-icon icon="{{state_attr(global,'icon')}}"></ha-icon>&nbsp;{{risk[state_attr(global,'level')]|upper}}
  {% else %}
  <center><ha-icon icon="mdi:shield-check"></ha-icon> &nbsp; NESSUN EVENTO CRITICO
  <center>{{'' if summary == 'unknown' else summary }}
  {% endif %}

