type: custom:auto-entities # CONDITIONAL ULTIMI xx TERREMOTI
show_empty: false
sort:
  {attribute: publication_date, method: attribute, reverse: true, count: 3, first: 1}
filter:
  include:
    - entity_id: geo_location.*
      attributes:
        source: ingv_centro_nazionale_terremoti
      # options:
card:
  type: markdown
  entity_id: this.entity_id
  style: |
    ha-card {background: none; border-radius: 0px; box-shadow: none;}
  content: >
    <center>LISTA ULTIMI TERREMOTI</center>
    {% set url = "http://shakemap.rm.ingv.it/shake/{}/download/{}.jpg" %}
    {% set url2 = "https://e.hsit.it/{}/{}_{}.jpg" %}
    {% set code = {1:'White', 2:'Green', 3:'Yellow', 4:'Orange', 5:'Red'} %}
    {% for e in config.entities %} {% set id = state_attr(e.entity, 'event_id') %}<br>
    <font color= var(--primary-text-color)>
    <font color = var(--disabled-text-color)>{{state_attr(e.entity, 'publication_date').strftime("%d/%m %H:%M") }}</font>
    <font color = {{code[state_attr(e.entity, 'magnitude')|int]}}>
    <ha-icon icon="{{state_attr(e.entity, 'icon')}}"></ha-icon></font> {{state_attr(e.entity, 'friendly_name')}} 🏡➡ {{states(e.entity)}} Km
    </font>
    {% if state_attr(e.entity, 'magnitude') >= 3 %}
    <center> 
    <a href="{{state_attr(e.entity, 'image_url')}}"> <img src="{{state_attr(e.entity, 'image_url')}}" height="50"></a>
    <a href="{{url.format(id,'pga')}}"> <img src="{{url.format(id,'pga')}}" height="50" ></a>
    <a href="{{url.format(id,'pgv')}}"> <img src="{{url.format(id,'pgv')}}" height="50" ></a>
    <a href="{{url.format(id,'tvmap')}}"> <img src="{{url.format(id,'tvmap')}}" height="50" ></a>
    <a href="{{url2.format(id,id,'mcs')}}"> <img src="{{url2.format(id,id,'mcs')}}" height="50" ></a>
    <a href="{{url2.format(id,id,'filledMCS')}}"> <img src="{{url2.format(id,id,'filledMCS')}}" height="50" ></a>
    <a href="{{url2.format(id,id,'emailMap')}}"> <img src="{{url2.format(id,id,'emailMap')}}" height="50" ></a>
    </center> 
    {% endif %}
    {%- endfor %}


