type: conditional # TERREMOTO conditional
conditions:
  - entity: binary_sensor.lastquake
    state: 'on'
card:
  type: vertical-stack # TEREMOTO divider Markcdown https://www.google.com/maps/search/?api=1&query={{lat}},{{long}}
  cards:
  - type: custom:text-divider-row
    text:  TERREMOTO
  - type: markdown
    style: |
      ha-card {background: none; border-radius: 0px; box-shadow: none; color: var(--secondary-text-color);}
      .card-content {padding: 0}
    content: >-
      <!-- Setting -->
        {%- set person = 'person.claudio' -%}
        {%- set url = "http://shakemap.rm.ingv.it/shake/{}/download/{}.jpg" -%}
        {%- set entityid = 'binary_sensor.lastquake' -%}
        {%- set id = state_attr(entityid, 'event_id') -%}
        {%- set data_utc = state_attr(entityid, 'publication_date') -%}
        {%- set magnitudo = (state_attr(entityid, 'magnitude')|float) if not none else '0' -%}
        {%- set code = {0:'White', 1:'Green', 2:'Yellow', 3:'Orange', 4:'Red'} -%}
        {%- set color = code[state_attr('binary_sensor.lastquake', 'level')|int] -%}
        {%- set lat = state_attr(entityid, 'lat') -%}
        {%- set long = state_attr(entityid, 'long') -%}
      <font color= var(--primary-text-color)>

      **<font color={{color}}>{{as_timestamp(data_utc)|timestamp_custom ('%H:%M:%S del %d/%m/%Y')}}</font>**<br><br>
      Un terremoto di magnitudo **<font color={{color}}>{{magnitudo}}</font>**<br>
      è avvenuto nella zona: [{{state_attr(entityid, 'region')}}](http://maps.google.com/maps?z=8&q=loc:{{lat}}+{{long}})<br>
      a <font color={{color}}>**{{state_attr(entityid, 'distance')}}**</font> km da casa,<br>
      con coordinate geografiche (lat, long) {{lat}},{{long}}.<br>
      {{("Tu ti trovi a " ~ distance(lat, long, person)) ~ " km dall'epicentro." if is_state(person, 'not_home') else ''}}
      </font><br>
      {% if magnitudo >= 3 %}
      [Shakemap]({{url.format(id,'intensity')}}) ~ 
      [PGA]({{url.format(id,'pga')}}) ~ [PGV]({{url.format(id,'pgv')}}) ~ [TvMap]({{url.format(id,'tvmap')}}) ~ [TvMap2]({{url.format(id,'tvmap_bare')}}) ~ 
      [HaiSentitoIlTerremoto](http://eventi.haisentitoilterremoto.it/{{id}}/{{id}}_mcs.jpg)

      <!-- Scegli il titpo di immagine da visualizzare [intensity,pga,pgv,tvmap,tvmap_bare] -->
        <img src="{{url.format(id,'intensity')}}"/>
        <!-- <img src="{{url.format(id,'pga')}}"/> -->
      {% endif %}

      [INGV](http://terremoti.ingv.it/) ~ [HaiSentitoIlTerremoto Web](http://www.haisentitoilterremoto.it/)

  - !include markdown_terremoti.yaml

# search # <a href="https://www.google.com/maps/search/?api=1&query={{lat}},{{long}}">{{state_attr(entityid, 'region')}}</a>
  # zona: [{{state_attr(entityid, 'region')}}](https://www.google.com/maps/search/?api=1&query={{lat}},{{long}})

# center map # https://www.google.com/maps/@?api=1&map_action=map&center={{lat}},{{long}}&zoom=12&basemap=satellite
# Origin # https://www.google.com/maps/dir/?api=1&origin={{lat}},{{long}}&zoom=12&basemap=satellite
# Home-destination # [{{state_attr(entityid, 'region')}}](https://www.google.com/maps/dir/?api=1&origin={{state_attr('zone.geoalert','latitude')}},{{state_attr('zone.geoalert','longitude')}}&destination={{lat}},{{long}}&travelmode=walking) 
# https://www.google.com/maps/place/{{lat}}+{{long}}/@{{lat}},{{long}},12z
# Phone
  # http://maps.google.com/maps?z=12&q=loc:{{lat}}+{{long}}
