type: conditional
conditions:
  - entity: sensor.meteoalarm_custom
    state_not: '0'
card:
  type: vertical-stack
  cards:
    - type: custom:text-divider-row
      text: METEO ALARM CUSTOM
    - type: markdown
      style: |
        ha-card {background: none; border-radius: 0px; box-shadow: none;}
      content: >
        {%set day = {'today':'Oggi', 'tomorrow':'Domani'} %}
        {%set color = {'Green':'Verde', 'Yellow':'Gialla', 'Orange':'Arancione', 'Red':'Rossa'} %}
        {%set dict_code={'Green':'1','Yellow':'2','Orange':'3','Red':'4'}%}
        {%set dict_type={'No-warnings': 'Nessun Avviso','Wind': 'Vento',
        'Snow/ice': 'Neve-Ghiaccio','Thunderstorms': 'Temporali',
        'Fog': 'Nebbia','High/temperature': 'Caldo intenso',
        'Low-temperature': 'Freddo intenso',
        'Costal-event': 'Eventi Costieri','Forest/fire': 'Incendi bischivi',
        'Avalanche': 'Valanghe','Rain': 'Pioggia',
        'Unavailable': 'Non disponibile','Flooding': 'Alluvione',
        'Rain/flooding': 'Pioggia/Alluvione'}%}
        {%set type={'No-warnings': '0','Wind': '1',
        'Snow/ice': '2','Thunderstorms': '3',
        'Fog': '4','High/temperature': '5',
        'Low-temperature': '6',
        'Costal-event': '7','Forest/fire': '8',
        'Avalanche': '9','Rain': '10',
        'Unavailable': '11','Flooding': '12',
        'Rain/flooding': '13'}%}
        {%- if not is_state('sensor.meteoalarm_custom', '0') -%}
          {%- for s  in ['today', 'tomorrow'] -%}
            {%- set v = state_attr('sensor.meteoalarm_custom', s) -%}
              {%- if v -%}
                {%- for d  in v %}
                {% set l = dict_code[d['code']] %}
                {% set t = type[d['event']] %}
        **{{day[s]}}:** <img src="https://www.meteoalarm.eu/documents/rss/wflag-l{{'0' if l == none else l.split(';')[0]}}-t{{'0' if t == none else t.split(';')[0]}}.jpg"> <font color= {{d['code']}}>**{{dict_type[d['event']]}}** </font>
        **Allerta:** <font color= {{d['code']}}><ha-icon icon="{{'mdi:numeric-'~dict_code[d['code']]~'-box'}}" style="width: 36px; height: 36px;"></ha-icon>{{color[d['code']]}}</font><br>
        Descrizione: <font color= var(--primary-text-color)>{{d['italiano']}}</font><br>
        Data: <font color= var(--primary-text-color)>{{d['start']|trim("CEST")|replace('.','/')}} - {{d['end']|trim("CEST")|replace('.','/')}}</font><br>
                {%- endfor -%}
              {%- endif -%}
          {%- endfor -%}
        {%- endif %}

        [MeteoAlarm]({{state_attr('binary_sensor.meteoalarm', 'web')}}) 

#{{'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;' if s == 'today' else ''}}